name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform_init_and_apply:
    name: "Terraform Init and Apply"

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      DEPLOYMENT_TOKEN: $(terraform output static_web_app_api_token | tr -d '"')

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Terraform output
        id: tfoutput
        run: |
          echo $env.DEPLOYMENT_TOKEN
          echo "Learn bash programming from LinuxHint.com"
          my_static_web_app_api_token=$(terraform output static_web_app_api_token | tr -d '"')
          echo "$my_static_web_app_api_token"
          echo "DONE DONE DONE"
          echo ${{ env.DEPLOYMENT_TOKEN }}
          echo "Heick"

      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1        
        run: |
          echo ${{ env.DEPLOYMENT_TOKEN }}          
        with:          
          azure_static_web_apps_api_token: ${{ env.DEPLOYMENT_TOKEN }} # ${{ secrets.AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
  
  # build_and_deploy_job:
  #   #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Build and Deploy Job
  #   needs: terraform_init_and_apply
  #   steps:  
  #     - name: Terraform output
  #       id: tfoutput2
  #       run: |
  #         echo ${{ needs.terraform_init_and_apply.outputs.static_web_app_api_token }}
  #         echo "$(FOO)"
  #         echo $(terraform output static_web_app_api_token | tr -d '"')

  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - name: Build And Deploy
  #       id: builddeploy
  #       uses: Azure/static-web-apps-deploy@v1        
  #       with:
  #         azure_static_web_apps_api_token: $(terraform output static_web_app_api_token) #${{ secrets.AZURE_STATIC_WEB_APP_DEPLOYMENT_TOKEN }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
  #         action: "upload"
  #         ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
  #         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
  #         app_location: "/src" # App source code path
  #         api_location: "api" # Api source code path - optional
  #         output_location: "" # Built app content directory - optional
  #         ###### End of Repository/Build Configurations ######
 